//FileSystem/Templates/Licenses/license-default.txt to change this license
 //* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 //*/
package hospital;

/**
 *
 * @author Nasser
 */
public class testframe extends javax.swing.JFrame {

    /**
     * Creates new form testframe
     */
    public testframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tmLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tnLabel2 = new javax.swing.JLabel();
        tidLabel3 = new javax.swing.JLabel();
        tntextf1 = new javax.swing.JTextField();
        tidtextf2 = new javax.swing.JTextField();
        tinbutton1 = new javax.swing.JButton();
        tdelbutton2 = new javax.swing.JButton();
        tupbutton3 = new javax.swing.JButton();
        tsebutton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tetable1 = new javax.swing.JTable();
        tbbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tmLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        tmLabel1.setText("Test Form");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tnLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tnLabel2.setText("Test Name");

        tidLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tidLabel3.setText("Test Id");

        tidtextf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidtextf2ActionPerformed(evt);
            }
        });

        tinbutton1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tinbutton1.setText("Insert");
        tinbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinbutton1ActionPerformed(evt);
            }
        });

        tdelbutton2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tdelbutton2.setText("Delete");
        tdelbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdelbutton2ActionPerformed(evt);
            }
        });

        tupbutton3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tupbutton3.setText("Update");
        tupbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tupbutton3ActionPerformed(evt);
            }
        });

        tsebutton4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tsebutton4.setText("search");
        tsebutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsebutton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tidLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tidtextf2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(tnLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tntextf1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tinbutton1)
                            .addComponent(tupbutton3))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tdelbutton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tsebutton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tntextf1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tidtextf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinbutton1)
                    .addComponent(tdelbutton2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tupbutton3)
                    .addComponent(tsebutton4))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tetable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "test_id", "test_name", "test_data", "test_time", "test_result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tetable1);

        tbbutton1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        tbbutton1.setText("Back");
        tbbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(tbbutton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(tmLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tmLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(tbbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidtextf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidtextf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidtextf2ActionPerformed

    private void tinbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinbutton1ActionPerformed

    private void tdelbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdelbutton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdelbutton2ActionPerformed

    private void tupbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tupbutton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tupbutton3ActionPerformed

    private void tsebutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsebutton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsebutton4ActionPerformed

    private void tbbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new testframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tbbutton1;
    private javax.swing.JButton tdelbutton2;
    private javax.swing.JTable tetable1;
    private javax.swing.JLabel tidLabel3;
    private javax.swing.JTextField tidtextf2;
    private javax.swing.JButton tinbutton1;
    private javax.swing.JLabel tmLabel1;
    private javax.swing.JLabel tnLabel2;
    private javax.swing.JTextField tntextf1;
    private javax.swing.JButton tsebutton4;
    private javax.swing.JButton tupbutton3;
    // End of variables declaration//GEN-END:variables
}
